mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #ex /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('thoughts/', views.thoughts, name='thoughts'),
    path('thoughts/list_all/', views.ThoughtListView.as_view(), name='thought_list'),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Thought(models.Model):
    title = models.CharField(max_length=100, default='')
    thought= models.CharField(max_length=1000, default='')
    pub_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

polls/forms.py
from django import forms
from .models import Thought
from django.utils import timezone

class ThoughtForm(forms.ModelForm):
    class Meta:
        model = Thought
        fields = ['title', 'thought']
        widgets = {
            'title': forms.TextInput(
				attrs={
					'class': 'form-control'
					}
				),
            'thought': forms.Textarea(
				attrs={
					'class': 'form-control'
					}
				),
			}
    # title_text = forms.CharField(max_length=200)
    # thought_text = forms.CharField(max_length=1000)
    # pub_date = forms.DateTimeField()

    # def __str__(self):
    #     return self.thought_text

polls/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question, Thought
from .forms import ThoughtForm

#View of latest few Questions
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
            """
            Return the last five published questions (not including those set to be
            published in the future).
            """
            return Question.objects.filter(
                pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]


#View of a Question's text
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


#View of a Question's results
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


#Handles voting for a particular Question
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
           'question': question,
           'error_message': "You didn't select a choice.", 
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

class ThoughtListView(generic.ListView):
    template_name = "polls/thought_list.html"
    context_object_name = 'thought_list'

    def get_queryset(self):
        return Thought.objects.order_by('-pub_date')[:]

#Handles thought submission
def thoughts(request):
    if request.method == 'POST':
        form = ThoughtForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('polls:thought_list'))
    else:
        form = ThoughtForm()
    return render(request, 
                    'polls/thoughts.html',
                    {'form' : form})

polls/templates/polls/detail.html
{% load static %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<html>
    <body style="background-color:#000000;" >
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#da2800;">
            <img class="rounded mr-2" src="{% static 'polls/images/PhilSwiftThumb.jpg' %}" width="40" height="40" alt="">
            <a class="navbar-brand" href="/polls">Flex Town</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/polls">Latest<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Archive<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Thoughts
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/polls/thoughts">Record Thought</a>
                    <a class="dropdown-item" href="/polls/thoughts/list_all">View Thoughts</a>
                    </div>
                </li>
                </ul>
            </div>
        </nav>
        <div class="mt-5 m-5 p-2 rounded text-white" style="background-color: #242424;">
            <h2 style="text-align: center;">{{ question.question_text }}</h2>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
            <div class="rounded p-2 m-2" style="background-color: #353535;">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            </div>
            {% endfor %}
            <div style="text-align: center;">
                <input class="pr-5 pl-5 text-white" style="background-color: #353535;" type="submit" value="Vote">
            </div>
            </form>
        </div>
    </body>
    <div class="footer fixed-bottom text-white p-2" style="background-color:#da2800;">
        <small>Flex Town &copy; 2021 Thomas Keathley</small>
    </div>
</html>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<html>
    <body style="background-color:#000000;" >
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#da2800;">
            <img class="rounded mr-2" src="{% static 'polls/images/PhilSwiftThumb.jpg' %}" width="40" height="40" alt="">
            <a class="navbar-brand" href="/polls">Flex Town</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/polls">Latest<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Archive<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Thoughts
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/polls/thoughts">Record Thought</a>
                    <a class="dropdown-item" href="/polls/thoughts/list_all">View Thoughts</a>
                    </div>
                </li>
                </ul>
            </div>
        </nav>

        {% if latest_question_list %}
            <ul class="mt-5 mr-5">
            {% for question in latest_question_list %}
                <li><div class="text-light rounded p-2 mb-4" style="background-color: #242424;">
                    <a class="text-white" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </li></div>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </body>

    <div class="footer fixed-bottom text-white p-2" style="background-color:#da2800;">
      <small>Flex Town &copy; 2021 Thomas Keathley</small>
    </div>
</html>

polls/templates/polls/results.html
{% load static %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<html>
    <body style="background-color:#000000;" >
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#da2800;">
            <img class="rounded mr-2" src="{% static 'polls/images/PhilSwiftThumb.jpg' %}" width="40" height="40" alt="">
            <a class="navbar-brand" href="/polls">Flex Town</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/polls">Latest<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Archive<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Thoughts
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/polls/thoughts">Record Thought</a>
                    <a class="dropdown-item" href="/polls/thoughts/list_all">View Thoughts</a>
                    </div>
                </li>
                </ul>
            </div>
        </nav>

        <div class="mt-5 m-5 p-2 rounded text-white" style="background-color: #242424;">
            <h2 style="text-align: center;">{{ question.question_text }}</h2>

            <ul>
            {% for choice in question.choice_set.all %}
            <li class="rounded p-2 mr-2 mt-2 mb-2" style="background-color: #353535;">
                {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </li>
            {% endfor %}
            </ul>

            <div style="text-align: center;">
                <a class="text-white rounded p-1" style="background-color: #353535;" href="{% url 'polls:detail' question.id %}">Vote again?</a>
            </div>
        </div>
    <div class="footer fixed-bottom text-white p-2" style="background-color:#da2800;">
        <small>Flex Town &copy; 2021 Thomas Keathley</small>
    </div>
</html>

polls/templates/polls/thought_list.html
{% load static %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<html>
    <body style="background-color:#000000;" >
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#da2800;">
            <img class="rounded mr-2" src="{% static 'polls/images/PhilSwiftThumb.jpg' %}" width="40" height="40" alt="">
            <a class="navbar-brand" href="/polls">Flex Town</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/polls">Latest<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Archive<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Thoughts
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/polls/thoughts">Record Thought</a>
                    <a class="dropdown-item" href="/polls/thoughts/list_all">View Thoughts</a>
                    </div>
                </li>
                </ul>
            </div>
        </nav>

        {% if thought_list %}
            <dl class="mt-5 m-5">
                {% for thought in thought_list %}
                <div class="text-light rounded p-1 mb-4" style="background-color: #242424;">
                    <dt class="p-2"><h4>{{ thought.title }}</h4></dt>
                    <dd class="text-light rounded p-1 mr-3 ml-3" style="background-color: #353535;">
                        {{ thought.thought }}
                    </dd>
                </div>
                {% endfor %}
            </dl>
        {% else %}
            <p>No thoughts are available.</p>
        {% endif %}
    </body>

    <div class="footer fixed-bottom text-white p-2" style="background-color:#da2800;">
        <small>Flex Town &copy; 2021 Thomas Keathley</small>
    </div>
</html>

polls/templates/polls/thoughts.html
{% load static %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<html>
    <body style="background-color:#000000;" >
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#da2800;">
            <img class="rounded mr-2" src="{% static 'polls/images/PhilSwiftThumb.jpg' %}" width="40" height="40" alt="">
            <a class="navbar-brand" href="/polls">Flex Town</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/polls">Latest<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Archive<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Thoughts
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/polls/thoughts">Record Thought</a>
                    <a class="dropdown-item" href="/polls/thoughts/list_all">View Thoughts</a>
                    </div>
                </li>
                </ul>
            </div>
        </nav>
        
        <div class="mt-5 m-5 p-2 rounded text-white" style="background-color: #242424;">
            <h2 class="m-2" style="text-align: center;">Your Thoughts</h2>

            <form action="{% url 'polls:thoughts' %}" method="post">
                {% csrf_token %}
                <div class="m-2">
                    <label class="mb-2">Title:</label>
                    {{ form.title }}<br>
                    <p class="mb-2 mt-2">Thought:</p>
                    {{ form.thought}}<br>
                </div>
                <div style="text-align: center;">
                    <button  class="pr-5 pl-5 text-white" style="background-color: #353535;" class='button' type='submit'>Submit</button>
                </div>
            </form>
        </div>

    <div class="footer fixed-bottom text-white p-2" style="background-color:#da2800;">
        <small>Flex Town &copy; 2021 Thomas Keathley</small>
    </div>
</html>